
names = {'fraction of object intensities above 25', ...
         'fraction of object intensities above 51', ...
         'fraction of object intensities above 76', ...
         'fraction of object intensities above 102', ...
         'fraction of object intensities above 127', ...
         'fraction of object intensities above 153', ...
         'fraction of object intensities above 178', ...
         'fraction of object intensities above 204', ...
         'fraction of object intensities above 229', ...
};

slfnames = repmat({''},[1 length(names)]);
